//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScratchNet.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScratchNet.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 can not convert {0} to {1} 的本地化字符串。
        /// </summary>
        internal static string CanNotConvertException {
            get {
                return ResourceManager.GetString("CanNotConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 collection type including stack, queue and list 的本地化字符串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 complex data structure, including binary tree, and linked list 的本地化字符串。
        /// </summary>
        internal static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Execution Aborted 的本地化字符串。
        /// </summary>
        internal static string ExecutionAborted {
            get {
                return ResourceManager.GetString("ExecutionAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to new the object 的本地化字符串。
        /// </summary>
        internal static string FailedNewException {
            get {
                return ResourceManager.GetString("FailedNewException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 index is out of the range 的本地化字符串。
        /// </summary>
        internal static string IndexOutOfRangeException {
            get {
                return ResourceManager.GetString("IndexOutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invliad format before =, only variable can be placed here 的本地化字符串。
        /// </summary>
        internal static string InvalidBeforeEqual {
            get {
                return ResourceManager.GetString("InvalidBeforeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 invalid value format: &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        internal static string InvalidFormat {
            get {
                return ResourceManager.GetString("InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value is not an array 的本地化字符串。
        /// </summary>
        internal static string NotArrayException {
            get {
                return ResourceManager.GetString("NotArrayException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value is not boolean value 的本地化字符串。
        /// </summary>
        internal static string NotBoolean {
            get {
                return ResourceManager.GetString("NotBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value is not an array, list or dictionary 的本地化字符串。
        /// </summary>
        internal static string NotCollectionException {
            get {
                return ResourceManager.GetString("NotCollectionException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not convert {0} to double 的本地化字符串。
        /// </summary>
        internal static string NotConvertToDoubleException {
            get {
                return ResourceManager.GetString("NotConvertToDoubleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not convert {0} to float 的本地化字符串。
        /// </summary>
        internal static string NotConvertToFloatException {
            get {
                return ResourceManager.GetString("NotConvertToFloatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not convert {0} to integer 的本地化字符串。
        /// </summary>
        internal static string NotConvertToIntegerException {
            get {
                return ResourceManager.GetString("NotConvertToIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can not conver {0} to long 的本地化字符串。
        /// </summary>
        internal static string NotConvertToLongException {
            get {
                return ResourceManager.GetString("NotConvertToLongException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Value is not integer 的本地化字符串。
        /// </summary>
        internal static string NotIntegerException {
            get {
                return ResourceManager.GetString("NotIntegerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value is not number 的本地化字符串。
        /// </summary>
        internal static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value is not an array 的本地化字符串。
        /// </summary>
        internal static string NotNumberException {
            get {
                return ResourceManager.GetString("NotNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value is not a string 的本地化字符串。
        /// </summary>
        internal static string NotStringException {
            get {
                return ResourceManager.GetString("NotStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The value is not a string or number 的本地化字符串。
        /// </summary>
        internal static string NotStringNumberException {
            get {
                return ResourceManager.GetString("NotStringNumberException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No value assined 的本地化字符串。
        /// </summary>
        internal static string NoValueAssigned {
            get {
                return ResourceManager.GetString("NoValueAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null Exception 的本地化字符串。
        /// </summary>
        internal static string NullException {
            get {
                return ResourceManager.GetString("NullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Null Exception 的本地化字符串。
        /// </summary>
        internal static string NullException1 {
            get {
                return ResourceManager.GetString("NullException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value can not be null 的本地化字符串。
        /// </summary>
        internal static string NullException2 {
            get {
                return ResourceManager.GetString("NullException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only variable can accepted 的本地化字符串。
        /// </summary>
        internal static string OnlyVariableAccept {
            get {
                return ResourceManager.GetString("OnlyVariableAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter can not be null 的本地化字符串。
        /// </summary>
        internal static string ParameterNullException {
            get {
                return ResourceManager.GetString("ParameterNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 string value only support += 的本地化字符串。
        /// </summary>
        internal static string StringOnlySupport {
            get {
                return ResourceManager.GetString("StringOnlySupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test condition can not be null 的本地化字符串。
        /// </summary>
        internal static string TestNullException {
            get {
                return ResourceManager.GetString("TestNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection 的本地化字符串。
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Structure 的本地化字符串。
        /// </summary>
        internal static string Title1 {
            get {
                return ResourceManager.GetString("Title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown exception 的本地化字符串。
        /// </summary>
        internal static string UnknowException {
            get {
                return ResourceManager.GetString("UnknowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 value can not be null 的本地化字符串。
        /// </summary>
        internal static string ValueNullException {
            get {
                return ResourceManager.GetString("ValueNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable already defined 的本地化字符串。
        /// </summary>
        internal static string VariableDefinedExcepiton {
            get {
                return ResourceManager.GetString("VariableDefinedExcepiton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Variable name can not be null 的本地化字符串。
        /// </summary>
        internal static string VariableNameException {
            get {
                return ResourceManager.GetString("VariableNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 variable {0} was not defined 的本地化字符串。
        /// </summary>
        internal static string VariableNotDefined {
            get {
                return ResourceManager.GetString("VariableNotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 the variable value can not be null 的本地化字符串。
        /// </summary>
        internal static string VariableNullException {
            get {
                return ResourceManager.GetString("VariableNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong string format 的本地化字符串。
        /// </summary>
        internal static string WrongStringFormat {
            get {
                return ResourceManager.GetString("WrongStringFormat", resourceCulture);
            }
        }
    }
}
